name: CI-CD Pipeline (Petclinic)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: http://13.235.245.255:9000
      NEXUS_URL: http://13.235.245.255:8081
      TOMCAT_URL: http://13.235.245.255:8080

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build & Test
        run: mvn clean install

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=petclinic \
          -Dsonar.host.url=${SONAR_HOST_URL} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Deploy to Nexus
        run: |  
          mvn deploy -DskipTests \
          -DaltDeploymentRepository=nexus::default::http://13.235.245.255:8081/repository/maven-releases/
        

      - name: Deploy WAR to Tomcat
        run: |
          curl -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
          --upload-file target/*.war \
          "${TOMCAT_URL}/manager/text/deploy?path=/petclinic&update=true"
